# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: 'x86'
        
    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install tinyaes
    - name: AutoBuild
      run: |
        pyinstaller stopclass.py -w -F --key ffdghjofjhthrffd
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: exeFile
        path: dist/stopclass.exe

